apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-modeling
spec:
  selector:
    matchLabels:
      app: cloud-modeling                                   
  replicas: 1
  template:
    metadata:
      labels:
        app: cloud-modeling
    spec:
      containers:
      - image: activiti/activiti-modeling-app:7.1.0.M5
        name: cloud-modeling
        env:
        - name: APP_CONFIG_OAUTH2_HOST
          value: "http://195.19.40.232/auth/realms/activiti"
        - name: APP_CONFIG_OAUTH2_CLIENTID
          value: "activiti"
        - name: API_URL
          value: "http://195.19.40.232"
        - name: BASE_PATH
          value: /modeling/
        - name: APP_CONFIG_BPM_HOST
          value: "http://195.19.40.232"
        - name: APP_CONFIG_OAUTH2_REDIRECT_SILENT_IFRAME_URI
          value: /modeling/assets/silent-refresh.html
        - name: APP_CONFIG_OAUTH2_REDIRECT_LOGIN
          value: /modeling
        - name: APP_CONFIG_OAUTH2_REDIRECT_LOGOUT
          value: /modeling

---

apiVersion: v1
kind: Service
metadata:
  name: cloud-modeling
spec:
  selector:
    app: cloud-modeling
  ports:
  - name: "80"
    port: 80
    targetPort: 80
status:
  loadBalancer: {}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud-modeling
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
    nginx.ingress.kubernetes.io/proxy-buffers: "64k"
    nginx.ingress.kubernetes.io/proxy-busy-buffers: "64k"
    nginx.ingress.kubernetes.io/fastcgi-buffer-size: "32k"
    nginx.ingress.kubernetes.io/fastcgi-buffers: "4"
spec:
  rules:
  - http:
      paths:
      - path: /modeling/?(.*)
        pathType: Prefix
        backend:
          service:
            name: cloud-modeling
            port:
              number: 80